### ISSUE TITLE
Output is not escaped correctly

### ISSUE THREAD

**Issue by svick** [CodeConversations/CodeConversations#1]
In the keynote, you can see that when @shanselman uses `Console.WriteLine` with a string containing an apostrophe, the output shows `&#39;`, when it should be just `'`:

![](https://user-images.githubusercontent.com/287848/82356822-6992da80-9a04-11ea-9d65-5116c1e2806e.png)

AFAICT the problematic code is here:

https://github.com/CodeConversations/CodeConversations/blob/0bb738384982d32a89c48a422af02339c232c6e9/src/Bots/CodeConversationsBot.cs#L153

I believe `HtmlEncode()` is not the correct thing to do here, though some escaping will probably be necessary.

**Comment by bradygaster** [comment]
@svick - want to submit PR #1?

**Comment by svick** [comment]
@bradygaster I'm not sure what is the right way to escape `content` (e.g. if `content` contains ` ``` `, could I use quadruple-backticks block here to display that correctly?) and based on [the guide](https://github.com/CodeConversations/CodeConversations/blob/master/BuildCodeBot.md), trying it out would be way too complicated. So, no, I'll leave the PR to someone else.

**Comment by bradygaster** [comment]
I think it'd be as simple as changing it to `HtmlDecode`. cc @colombod - did one of us use the wrong method here? seems like we want decode.

**Comment by colombod** [comment]
I think we no longer need that method. We did it because previously we were doing output in the viewer only while that one sends back messages, is probably not needed at all.
